ARIBA run with this command:
/home/jhuang/anaconda3/envs/bengal/bin/ariba prepareref prepareref -f db/virulencefinder/virulencefinder.fa -m db/virulencefinder/virulencefinder.tsv db/virulencefinder/prepareref.virulencefinder
from this directory: /home/jhuang/Tools/ST772

ARIBA version: 2.12.0

External dependencies:
bowtie2	2.3.4.3	/home/jhuang/anaconda3/envs/bengal/bin/bowtie2
cdhit	4.7	/home/jhuang/anaconda3/envs/bengal/bin/cd-hit-est
nucmer	3.1	/home/jhuang/anaconda3/envs/bengal/bin/nucmer

External dependencies OK: True

Python version:
3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 13:26:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]

Python packages:
ariba	2.12.0	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/ariba/__init__.py
bs4	4.6.3	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/bs4/__init__.py
dendropy	4.2.0	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/DendroPy-4.2.0-py3.5.egg/dendropy/__init__.py
pyfastaq	3.17.0	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/pyfastaq/__init__.py
pymummer	0.10.3	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/pymummer/__init__.py
pysam	0.10.0	/home/jhuang/anaconda3/envs/bengal/lib/python3.5/site-packages/pysam/__init__.py

Python packages OK: True

Everything looks OK: True
